name: FE:pychat.org

on:
  push:
    branches: [ anas ]
    paths: 
      - 'frontend/**'

jobs:
  upload_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.10'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            frontend/yarn-cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install npm dependencies
        run: |
          cd frontend 
          yarn config set cache-folder `pwd`/yarn-cache
          yarn install --frozen-lockfile
      - name: Build static files
        run: cd frontend && yarn run prod

      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANAS_ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.ANAS_PORT }} ${{ secrets.ANAS_HOST }} >> ~/.ssh/known_hosts
      - name: Copy static files to destination server
        run: |
          cd frontend
          tar c dist/ | ssh ${{ secrets.ANAS_SSH_USER }}@${{ secrets.ANAS_HOST }} -p ${{ secrets.ANAS_PORT }} "rm -rf /home/ubuntu/pychat/frontend/dist && tar x -C /home/ubuntu/pychat/frontend/"
