# This is a basic workflow to help you get started with Actions

name: Update pychat.org

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - run: echo "${{ secrets.ID_RSA }}" > /tmp/id_rsa && chmod 400 /tmp/id_rsa && ssh -i /tmp/id_rsa http@pychat.org -p 8886 "echo 3"
        env:
          SSH_RSA: ${{ secrets.ID_RSA }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PORT: ${{ secrets.PORT }} 
 
