# This is a basic workflow to help you get started with Actions

name: Update pychat.org

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: mkdir test; touch test/lol; cd test

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: copy static files to destination server
        run: echo "${{ secrets.ID_RSA }}" > /tmp/id_rsa ; pwd; tar c test/ | ssh -i /tmp/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} "rm -rf /tmp/dist && tar x -C /tmp/"
 
